---
galaxy_info:
  author: klen
  company: Stouts
  description: Installs and setup Grafana metrics dashboard
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system
  - monitoring
dependencies: []
